BUS_134_ROUTE_ID = '134'
LOWELL_LINE_ROUTE_ID = 'CR-Lowell'

TRADECENTER_STOP_ID = '10016'
LARAWAY_AT_WINCHESTER_STOP_ID = '9110'
WINCHESTER_CENTER_STOP_ID = 'Winchester Center'


INBOUND_DIRECTION_ID = '0'
OUTBOUND_DIRECTION_ID = '0'